### ISSUE TITLE
question for app.js

### ISSUE THREAD

**Issue by mayujie** [sandraisrael/Memory-Game-fend#4]
Hi could you please explain why in line 60, use object empty array? 
-->   [].forEach.call(cards, function(item) {

Thank you. @sandraisrael

**Comment by alexandredsl** [comment]
> 
> 
> Hi could you please explain why in line 60, use object empty array?
> --> [].forEach.call(cards, function(item) {
> 
> Thank you. @sandraisrael
Hi Mayujie, this use of object empty array is only to permite the use of array method forEach 

See this link for more details:
https://stackoverflow.com/questions/16053357/what-does-foreach-call-do-in-javascript

**Comment by mayujie** [comment]
Thank you very much! @alexandredsl

**Comment by ubaidisaev** [comment]
> > Hi could you please explain why in line 60, use object empty array?
> > --> [].forEach.call(cards, function(item) {
> > Thank you. @sandraisrael
> > Hi Mayujie, this use of object empty array is only to permite the use of array method forEach
> 
> See this link for more details:
> https://stackoverflow.com/questions/16053357/what-does-foreach-call-do-in-javascript

This line  
  --> let cards = [...card];  
converts NodeList to regular array, and so we can use more readable plain array mehod like ( map or forEach);

**Comment by uncooloj** [comment]
This issues has been responded to, so i would be closing it up
